name: Deploy to Endora (DogsShelterReact)

on:
  push:
    branches: [master]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build (Vite)
        run: npm run build
        # vite.config.js musí mít: base: '/DogsShelterReact/'

      - name: Deploy via FTPS (mirror only dist CONTENTS)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          passive: true
          # cílová složka na serveru
          server-dir: ${{ secrets.FTP_DIR }}DogsShelterReact/
          # <<< nahrává se jen OBSAH této složky
          local-dir: ./dist/
          # vyčistí cílovou složku a zrcadlí přesně to, co je v dist/
          dangerous-clean-slate: true
          # nic dalšího nevyřazujeme – nahrává se jen to, co je v dist/
          exclude: |
            **/.DS_Store
